### ISSUE TITLE
In Penalty Shoot-Outs some trials never end

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#152]
We currently face the issue that during the penalty shoot-outs some of the trials are not ending (usually the second or third one). So the game just stays in the state playing indefinitely and the next trial can't starte. Note that we don't face the issue for the test scenarios, they are all passing. However, we did not manage to successfully play an entire penalty shoot-out game at the moment because of this.

**Comment by medrimonia** [comment]
After looking at the code, it sounds to me that it's related to the `game.sent_finish` that might not be reset to `False` because state goes to `SET` before one tick of the `referee` is performed. This makes the condition that gets out of the penalty trial always false:

`if not game.sent_finish and game.state.seconds_remaining <= 0:`

I'll try a hotfix for this, but I think it's still good to parallelize on this issue.
