### ISSUE TITLE
Goalie position check looks at contact points and not Foot position

### ISSUE THREAD

**Issue by jgueldenstein** [RoboCup-Humanoid-TC/webots#164]
**Describe the Bug**
When the referee checks the position of the goalie, for example during a direct free kick, it checks the contact points. When the goalie robot moves on the line this can cause some of the contact points (for example the cleats) to be either inside or outside the field which causes a penalty for the robot.

**Expected behavior**
The robot should only be penalized if one or both (to be discussed) leaves the line. That means that the foot size needs to be taken into consideration.

**Comment by medrimonia** [comment]
This is a duplicate from #162 which properly describes the problem while opening more possibilities of answers to solve this problem.

> When the goalie robot moves on the line this can cause some of the contact points (for example the cleats) to be either inside or outside the field which causes a penalty for the robot.

The current implementation requires that the robot is simultaneously inside the field (i.e. has 1 contact point the field) and outside the field (i.e has 1 contact point outside the field):
`if player['outside_field'] or player['inside_field'] or abs(player['position'][1]) > GOAL_WIDTH:`

So this description is rather incorrect since the current condition for receiving a removal penalty is rather that one of the two following conditions is fulfilled:
1. None of them is inside
2. None of them is outside
